Repository arduino-libraries/ArduinoModbus, pull requests merged in 2024-02, with the labels that each got.

#115 add MODBUS explicit function codes to docs/api.md
  docs/api.md
  tags
Labels: type: enhancement, topic: documentation

#136 Correct documentation on `ModbusServer::poll()`
  docs/api.md
Labels: type: imperfection, topic: documentation

#142 Fix regression re report-size-deltas after updating actions/upload-artifact.
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#144 Remove accidentially committed file "tags".
  tags
Labels: type: imperfection, topic: code

#143 Fix regression: report size delta size on PR.
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
  .gitignore
Labels: type: imperfection, topic: infrastructure

#145 Fix size deltas report infrastructure configuration
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
Labels: type: imperfection, topic: infrastructure
